ra.core.print_start_message()
ra.core.enable_coat_checker()
ra.core.create_stones_triggers()
ra.core.create_bottle_triggers()
ra.core.read_orders_data()
ra.calendar.init()
ra.window:create()

tempTimer(3, [[ ra.core.login_pwd() ]])
tempTimer(5, [[ ra.window.refresh() ]])
tempTimer(ra.ra_login_timeout, [[ ra.core.refresh_token() ]])
tempTimer(10, [[ ra.core.show_enabling_switch_releasing_guards() ]])
tempTimer(13, [[ ra.core.download_all_online_data() ]])
tempTimer(19, [[ ra.core.check_plugin_update(false) ]])
tempTimer(20, [[ ra.core.read_enemylist_from_files() ]])
tempTimer(25, [[ ra.core.color_keygivers() ]])
tempTimer(27, [[ ra.core.download_drops_online_data() ]])
tempTimer(30, [[ ra.core.marge_yours_enymylists() ]])
tempTimer(35, [[ ra.alias.show_enemies_short() ]])
tempTimer(40, [[ ra.core.set_my_signature() ]])