return {
  "start",
  "drop_magic",
  "help",
--  "enemy_handling_old",
  "enemy_handling",
--  "sort_containers",
  "stones",
  "roman_numeral_converter",
  "mail",
  "admin",
  "detox",
  "team",
  "astrolabium",
  "keygivers",
  "selling",
  "download",
  "gaging",
  --"team_search",
  "notifcation_center",
  "drops",
  "calendar",
  "window",
  "carriage",
  "orders",
  "execute"
}